CREATE DATABASE IF NOT EXISTS gympro;

CREATE TABLE aluno(
	matricula INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
    senha VARCHAR(100) NOT NULL,
    cpf CHAR(11) NOT NULL,
    endereco VARCHAR(100),
    telefone VARCHAR(20)
);

CREATE TABLE adm(
	codigo INT NOT NULL PRIMARY KEY auto_increment,
	nome VARCHAR(100) NOT NULL,
    senha VARCHAR(100) NOT NULL
);


CREATE TABLE plano(
	codigo INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    tipo VARCHAR(100) NOT NULL,
    valor VARCHAR(100) NOT NULL
);